spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update

# Be explicit about springdoc being enabled in this profile.
# Documentation: https://springdoc.org/
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /openapi3.json
    enabled: true

server:
  # Heroku provides a port number in the env variable PORT.
  # This env variable is automatically created by Heroku.
  port: ${PORT}
  # Manually set BASE_URL env variable in Heroku for
  # Spring to load this config. The value should be
  # the Heroku url for your application.
  baseUrl: ${BASE_URL}