spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:file:~/myLocalDB;AUTO_SERVER=TRUE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /console

# Be explicit about springdoc being enabled in this profile.
# https://springdoc:org/#disabling-the-swagger-ui
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

server:
  port: 8080
  baseUrl: http://localhost:${server.port}